### ISSUE TITLE
decimal points in wrong places

### ISSUE THREAD

**Issue by bozofoz** [BazzerDv/quickclick#12]
**Describe the bug**

vibration engineer is listed as 10.0KC, should be 100KC
college dropout is listed as 15MC, should be 1.5MC
boss baby is listed as 15.0MC, should be 150MC
developer is listed as 15.0TC, should be 150TC

**Comment by BazzerDv** [comment]
Thanks, I will have a look at this

**Comment by BazzerDv** [comment]
This problem should have been fixed now :)
